### PR TITLE
Requesting code review for map feature

### PR DESCRIPTION
**Pull request by lovrodukic**

### CODE REVIEW

**Comment by lovrodukic** [comment]
I currently cannot put the TOKEN in a .env folder due to issues with CORS. Please review the rest of the code and see if the backend objects being loaded into the map popups look good

**Comment by adameza** [comment]
fix the conflicts before you merge this. Run `git merge main` and then `npm install` in FadeFinder/react-frontend and that should help. Else just go through manually and resolve those.

**Comment by drussell23** [comment]
I just reviewed the code for the map features for the website. Looks good to me!

**Comment by bsprague99** [comment]
Good work boss!

**Comment by lovrodukic** [comment]
I've created another pull request that added features and has no conflicts with main. Please review "geolocation-feature"

**Comment by lovrodukic** [comment]
I've fixed merge conflicts and will merge now. See my geolocation PR for further updates to the BarberFinder component

**Pull request merged**
